# Site settings
title: Your Website Title
description: A brief description of your website
url: "https://yourusername.github.io" # The base hostname & protocol for your site
baseurl: "" # The subpath of your site, e.g. /blog

# Build settings
theme: jekyll-theme-minimal # You can choose any Jekyll theme or use a custom one
markdown: kramdown
exclude: ["README.md", "Gemfile", "Gemfile.lock", "node_modules", "vendor", "_site"] # Files and folders to exclude from the build process
plugins: [] # If you're using any Jekyll plugins, list them here

# GitHub Pages settings
#remote_theme: arnabastro/arnabastro.github.io # If you're using a remote theme, specify it here
#include:
#  - main.css
github_pages: 
  enabled: true # Set to true if you're hosting on GitHub Pages
  branch: main # The branch you're deploying from

# Author settings
author:
  name: Arnab Sarkar
  email: arnabsar@mit.edu
  bio: A short bio about yourself

# Social links
social:
  - title: GitHub
    url: https://github.com/yourusername
  - title: Twitter
    url: https://twitter.com/yourtwitter
  # Add more social links as needed

# Navigation links
navbar_links:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Blog
    url: /blog
  # Add more navigation links as needed

